source input/user_input.sql;
source input/adult_input.sql;
source input/child_input.sql;
source input/financialaccount_input.sql;
source input/checking_input.sql;
source input/loan_input.sql;
source input/savings_input.sql
source input/accountcategory_input.sql;
source input/transacts_input.sql;
source input/transacts_input_extra.sql;