DROP PROCEDURE IF EXISTS addUser;
DROP PROCEDURE IF EXISTS deleteUser;
DROP PROCEDURE IF EXISTS deleteSavingsOnly;
DROP PROCEDURE IF EXISTS deleteLoanOnly;
DROP PROCEDURE IF EXISTS deleteCheckingOnly;
DROP PROCEDURE IF EXISTS reportAggregates;