source drop_tables.sql;
source drop_views.sql;
source drop_stored_procedures.sql;
source create_tables.sql;
source create_views.sql;
source addUser.sql;
source deleteUser.sql;
source deleteCheckingOnly.sql;
source deleteSavingsOnly.sql;
source deleteLoanOnly.sql;
source deleteCheckingFromFiAccount.sql;
source deleteSavingsFromFiAccount.sql;
source deleteLoanFromFiAccount.sql;
source updateAC.sql;
source updateAccount.sql;

source input/user_input.sql;
source input/adult_input.sql;
source input/child_input.sql;
source input/financialaccount_input.sql;
source input/checking_input.sql;
source input/loan_input.sql;
source input/savings_input.sql
source input/accountcategory_input.sql;
source input/transacts_input.sql;
source input/transacts_input_extra.sql;
