INSERT INTO AccountCategory(acctID, Category, Threshold)
VALUES
    (1, "groceries", 250),
    (1, "credit card payment", NULL),
    (1, "entertainment", NULL),
    (1, "food", NULL),
    (1, "gas", NULL),
    (1, "travel", NULL),
    (2, "groceries", NULL),
    (2, "credit card payment", NULL),
    (2, "entertainment", NULL),
    (2, "food", NULL),
    (2, "gas", NULL),
    (2, "travel", NULL),
    (3, "groceries", 250),
    (3, "credit card payment", NULL),
    (3, "entertainment", NULL),
    (3, "food", NULL),
    (3, "gas", NULL),
    (3, "travel", NULL),
    (3, "investment", NULL),
    (4, "groceries", 250),
    (4, "credit card payment", NULL),
    (4, "entertainment", NULL),
    (4, "food", NULL),
    (4, "gas", NULL),
    (4, "travel", NULL),
    (5, "groceries", 250),
    (5, "credit card payment", NULL),
    (5, "entertainment", NULL),
    (5, "food", 200),
    (5, "gas", NULL),
    (5, "travel", NULL),
    (5, "insurance", NULL),
    (5, "home improvement", NULL),
    (6, "groceries", 250),
    (6, "credit card payment", NULL),
    (6, "entertainment", NULL),
    (6, "food", NULL),
    (6, "gas", NULL),
    (6, "travel", NULL),
    (6, "insurance", NULL),
    (7, "gas", NULL),
    (11, "credit card", NULL),
    (11, "home improvement", NULL),
    (13, "credit card", NULL),
    (16, "auto loan", NULL),
    (17, "credit card", NULL),
    (18, "auto loan", NULL),
    (21, "general savings", NULL),
    (21, "home improvement fund", NULL),
    (21, "investment", NULL),
    (21, "travel fund", NULL),
    (22, "general savings", NULL),
    (22, "home improvement fund", NULL),
    (22, "investment", NULL),
    (22, "travel fund", NULL),
    (23, "general savings", NULL),
    (23, "home improvement fund", NULL),
    (23, "investment", NULL),
    (23, "travel fund", NULL),
    (24, "general savings", NULL),
    (24, "home improvement fund", NULL),
    (24, "investment", NULL),
    (24, "travel fund", NULL),
    (25, "general savings", NULL),
    (25, "home improvement fund", NULL),
    (25, "investment", NULL),
    (25, "travel fund", NULL);